# Generated by Django 4.2 on 2023-04-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('source', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite', models.BooleanField(default=False)),
                ('user', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
