# Generated by Django 4.2 on 2023-04-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.CharField(max_length=255),
        ),
    ]
